pan_controller:
    type: effort_controllers/JointPositionController
    joint: servo_pan_joint
    pid: {p: 20, i: 0.1, d: 1}

tilt_controller:
    type: effort_controllers/JointPositionController
    joint: servo_tilt_joint
    pid: {p: 20, i: 0.1, d: 1}

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  